# Generated by Django 4.0.3 on 2022-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Descripción')),
                ('tasks_state', models.CharField(blank=True, choices=[('', ''), ('Completa', 'Completa'), ('Incompleta', 'Incompleta')], default='', max_length=20, null=True, verbose_name='Estado tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ('-id',),
                'permissions': (('view_all_tasks', 'Can view all tasks'),),
            },
        ),
    ]
