# Generated by Django 4.0.3 on 2022-05-10 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de alta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el usuario debe ser tratado como activo.Desmarque esta opción en lugar de borrar la cuenta.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designa si el usuario puede iniciar sesión en este sitio administrativo.', verbose_name='es staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Las contraseñas sin procesar no se almacenan, por lo que no hay forma de ver la contraseña de este usuario, pero puede cambiarla utilizando <a href="password/">este formulario</a>.', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Usernames.', max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
